name       : mobile-broadband-provider-info
version    : 20120614
release    : 1
source     :
    - https://download.gnome.org/sources/mobile-broadband-provider-info/20120614/mobile-broadband-provider-info-20120614.tar.xz : 72507a732e0cd16cf27424bb094b1c7a03e2206c119ad124722a283e587755f1
license    : PUBLIC-DOMAIN
summary    : Mobile Broadband Provider Info
description: |
    Mobile Broadband Provider Info
builddeps  :
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
