name       : mobile-broadband-provider-info
version    : '20170310'
release    : 3
source     :
    - https://download.gnome.org/sources/mobile-broadband-provider-info/20170310/mobile-broadband-provider-info-20170310.tar.xz : 144f03c95e03a82c53425bae38bc9adcca5a5da3cac642d1931da6897a08b53b
license    : PUBLIC-DOMAIN
component  : network.util
summary    : Mobile Broadband Provider Info
patterns   :
    - devel : /usr/share/pkgconfig
description: |
    Mobile Broadband Provider Info
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
