name       : mobile-broadband-provider-info
version    : '20151214'
release    : 2
source     :
    - https://download.gnome.org/sources/mobile-broadband-provider-info/20151214/mobile-broadband-provider-info-20151214.tar.xz : 8ae45d6f10fed9750e259935804c4f40a4372bb119f0504187e4221896b205a4
license    : PUBLIC-DOMAIN
summary    : Mobile Broadband Provider Info
patterns   :
    - devel: /usr/share/pkgconfig
description: |
    Mobile Broadband Provider Info
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
